### ISSUE TITLE
eval error: Pretrained model on ImageNet

### ISSUE THREAD

**Issue by byerose** [inspire-group/compactness-robustness#2]
When I import the pretrained model on Imagenet  provided by you for evaulation, I find the following errors. My pytorch version is 1.10.0

```
Traceback (most recent call last):                                                                   
  File "debug.py", line 184, in <module>                                                             
    main()                                                                                           
  File "debug.py", line 179, in main                                                                 
    p1, _ = val(model, device, test_loader, criterion, args, writer)                                 
  File "/disk0/zhang/hydra/utils/eval.py", line 134, in adv                                          
    output = model(images)                                                                           
  File "/home/ams/anaconda3/envs/tf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 110
2, in _call_impl                                                                                     
    return forward_call(*input, **kwargs)                                                            
  File "/disk0/zhang/hydra/models/resnet.py", line 197, in forward                                   
    return self._forward_impl(x)                                                                     
  File "/disk0/zhang/hydra/models/resnet.py", line 180, in _forward_impl                             
    x = self.conv1(x)                                                                                
  File "/home/ams/anaconda3/envs/tf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 110
2, in _call_impl                                                                                     
    return forward_call(*input, **kwargs)                                                            
  File "/disk0/zhang/hydra/models/layers.py", line 69, in forward                                    
    adj = GetSubnet.apply(self.popup_scores.abs(), self.k)                                           
  File "/home/ams/anaconda3/envs/tf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 117
7, in __getattr__                                                                                    
    raise AttributeError("'{}' object has no attribute '{}'".format(                                 
AttributeError: 'SubnetConv' object has no attribute 'k'
```

**Comment by VSehwag** [comment]
This is because one have to first setup the model using `./utils/model/prepare_model`. Or you can call `set_prune_rate_model` with k=1.0, such that it sets the attribute k for SubnetConv.
