### ISSUE TITLE
Troubles loading checkpoint

### ISSUE THREAD

**Issue by giorgiopiras** [inspire-group/compactness-robustness#9]
Hi @VSehwag, thanks for your work once again. 
I am having some troubles loading the dict for the pretrained unpruned vgg16 network from dropbox. Here's my code

``` 
from models.vgg_cifar import vgg16
import torch 
from models.layers import SubnetConv, SubnetLinear
from torch.nn import Conv2d, Linear
import torch.nn as nn

model = vgg16(conv_layer=Conv2d, linear_layer=Linear, init_type="kaiming_normal", num_classes=10)
checkpoint = torch.load('/home/gpiras/hydra/vgg16_pretrained_dense.pth.tar', map_location=torch.device('cuda'))
model.load_state_dict(checkpoint['state_dict'], strict=True) 
model.eval()
```

And here's my error 

```
Initializing model with kaiming_normal
Traceback (most recent call last):
  File "/home/gpiras/hydra/Attack_pipeline.py", line 19, in <module>
    model.load_state_dict(checkpoint['state_dict'], strict=True) 
  File "/home/gpiras/anaconda3/envs/atmc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "features.2.weight", "features.5.weight", "features.12.weight", "features.19.weight", "features.26.weight". 
        Unexpected key(s) in state_dict: "features.30.weight", "features.31.weight", "features.31.bias", "features.31.running_mean", "features.31.running_var", "features.31.num_batches_tracked", "features.34.weight", "features.35.weight", "features.35.bias", "features.35.running_mean", "features.35.running_var", "features.35.num_batches_tracked", "features.37.weight", "features.38.weight", "features.38.bias", "features.38.running_mean", "features.38.running_var", "features.38.num_batches_tracked", "features.40.weight", "features.41.weight", "features.41.bias", "features.41.running_mean", "features.41.running_var", "features.41.num_batches_tracked", "features.1.weight", "features.1.bias", "features.1.running_mean", "features.1.running_var", "features.1.num_batches_tracked", "features.3.weight", "features.4.weight", "features.4.bias", "features.4.running_mean", "features.4.running_var", "features.4.num_batches_tracked", "features.8.weight", "features.8.bias", "features.8.running_mean", "features.8.running_var", "features.8.num_batches_tracked", "features.11.weight", "features.11.bias", "features.11.running_mean", "features.11.running_var", "features.11.num_batches_tracked", "features.15.weight", "features.15.bias", "features.15.running_mean", "features.15.running_var", "features.15.num_batches_tracked", "features.18.weight", "features.18.bias", "features.18.running_mean", "features.18.running_var", "features.18.num_batches_tracked", "features.20.weight", "features.21.bias", "features.21.running_mean", "features.21.running_var", "features.21.num_batches_tracked", "features.25.weight", "features.25.bias", "features.25.running_mean", "features.25.running_var", "features.25.num_batches_tracked", "features.27.weight", "features.28.bias", "features.28.running_mean", "features.28.running_var", "features.28.num_batches_tracked". 
        size mismatch for features.7.weight: copying a param with shape torch.Size([128, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
        size mismatch for features.10.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
        size mismatch for features.14.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
        size mismatch for features.17.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3, 3]).
        size mismatch for features.21.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
        size mismatch for features.24.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
        size mismatch for features.28.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
```

Any chance you could help me or maybe release an example snippet on how to load the model? 
Thank you

**Comment by VSehwag** [comment]
Hi @giorgiopiras, I tested loading the vgg checkpoint and it does load without any RuntimeError. Note that there are two errors when loading weight 1) shape mismatch in some weights 2) Missing keys. Latter suggests that most likely the dowloaded weights corresponds to a different vgg network (likely vgg13 or vgg11).
